### ISSUE TITLE
Bug when OS version installed is already macOS 10.14

### ISSUE THREAD

**Issue by sdpalmer** [laurentpertois/Mojave-Compatibility-Checker#1]
First time reporting an issue on GitHub, so hopefully I am doing this correctly.

On line 87, your if statement should actually be including 14 in the major version, by using **-le** instead of **-lt** otherwise this script incorrectly reports **False** for overall compatibility.

`if [[ "$OSVERSIONMAJOR" -ge 8 && "$OSVERSIONMAJOR" -le 14 || "$OSVERSIONMAJOR" -eq 7 && "OSVERSIONMINOR" -eq 5 ]]; then`

Sure we know a Mac is compatible if it is already on 10.14, but technically the script should still report **True** especially if we want to use this for scoping a reinstall of macOS 10.14 for somebody that has already upgraded.

**Comment by laurentpertois** [comment]
Hi @sdpalmer 

Will change that too
