### ISSUE TITLE
Missing test for iMac Pro model

### ISSUE THREAD

**Issue by sdpalmer** [laurentpertois/Mojave-Compatibility-Checker#2]
@laurentpertois I found that you are missing a test for the iMac Pro.  You might want to add another **elif** statement to your **if** block checking for compatibility:

`
elif [[ "$MODELNAME" == "iMacPro" && "$MODELVERSION" -ge 1 && "$MEMORYINSTALLED" -ge "$MINIMUMRAM" && "$FREESPACE" -ge "$MINIMUMSPACE" ]]; then
	    COMPATIBILITY="True"
fi
`

**Comment by laurentpertois** [comment]
Hi @sdpalmer,

Thanks for catching that one, I guess I wanted one so much but could not justify it that my brain has decided to forget its existence :)

Have a nice day, I'm making the change
