### ISSUE TITLE
Mac OS requirements incorrectly allow 10.7.5

### ISSUE THREAD

**Issue by sdpalmer** [laurentpertois/Mojave-Compatibility-Checker#3]
Apple's requirements at [https://support.apple.com/kb/SP777?locale=en_US](https://support.apple.com/kb/SP777?locale=en_US) state that it is Mac OS X 10.8 or later.

However, this script is still allowing 10.7.5.

**Comment by laurentpertois** [comment]
hi @sdpalmer 

Will change it too
